# Generated by Django 5.2 on 2025-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_workstep_workstepdefect_workstepprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='steps/'),
        ),
    ]
