# Generated by Django 5.2 on 2025-04-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_workstep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstep',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
