# Generated by Django 5.2 on 2025-04-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_workstep_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstepprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
