# Generated by Django 5.2 on 2025-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_workstepprogress_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstepprogress',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='workstep',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
