# Generated by Django 5.2 on 2025-05-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_workstepprogress_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('defect_type', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('authorized_by', models.CharField(max_length=100)),
                ('notify_email', models.EmailField(blank=True, max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.order')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.workstep')),
            ],
        ),
    ]
