# Generated by Django 5.2 on 2025-05-06 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_orderprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.order')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.workstep')),
            ],
            options={
                'unique_together': {('order', 'step', 'unit_number')},
            },
        ),
        migrations.DeleteModel(
            name='OrderProgress',
        ),
    ]
