# Generated by Django 5.2 on 2025-05-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_stepprogress_delete_orderprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepprogress',
            options={'ordering': ['unit_number', 'step__step_number']},
        ),
        migrations.RenameField(
            model_name='stepprogress',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.AlterUniqueTogether(
            name='stepprogress',
            unique_together={('order', 'unit_number', 'step')},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='workstep',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tools/'),
        ),
        migrations.AlterField(
            model_name='stepprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
