# Generated by Django 5.2 on 2025-05-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_stepprogress_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.component')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.order')),
            ],
            options={
                'unique_together': {('order', 'component')},
            },
        ),
    ]
