# Generated by Django 5.2 on 2025-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_ordercomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='unit_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
