# Generated by Django 5.2 on 2025-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_defect_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/'),
        ),
    ]
