# Generated by Django 5.2 on 2025-05-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_component_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstepprogress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='workstepprogress',
            name='step',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='WorkStepProgress',
        ),
    ]
