# Generated by Django 5.2 on 2025-06-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_remove_workstepprogress_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='tools',
        ),
        migrations.AddField(
            model_name='workstep',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='pos_x',
            field=models.PositiveIntegerField(default=0, help_text='px depuis le bord gauche'),
        ),
        migrations.AlterField(
            model_name='component',
            name='pos_y',
            field=models.PositiveIntegerField(default=0, help_text='px depuis le bord supérieur'),
        ),
        migrations.AlterField(
            model_name='component',
            name='z_index',
            field=models.PositiveIntegerField(default=1, help_text="Ordre d'empilement"),
        ),
    ]
