# Generated by Django 5.2 on 2025-06-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_remove_procedure_tools_workstep_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstep',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
