# Generated by Django 5.2 on 2025-06-27 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_workstep_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Défaut', 'verbose_name_plural': 'Défauts'},
        ),
        migrations.AlterModelOptions(
            name='ordercomponent',
            options={'verbose_name': 'Composant de commande', 'verbose_name_plural': 'Composants de commande'},
        ),
        migrations.AlterModelOptions(
            name='stepprogress',
            options={'ordering': ['unit_number', 'step__step_number'], 'verbose_name': "Progression de l'étape", 'verbose_name_plural': 'Progressions des étapes'},
        ),
        migrations.AlterModelOptions(
            name='workstep',
            options={'ordering': ['step_number'], 'verbose_name': 'Étape de travail', 'verbose_name_plural': 'Étapes de travail'},
        ),
        migrations.AlterModelOptions(
            name='workstepdefect',
            options={'ordering': ['-timestamp'], 'verbose_name': "Défaut d'étape de travail", 'verbose_name_plural': "Défauts d'étapes de travail"},
        ),
        migrations.AlterField(
            model_name='codeitem',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name="Code unique identifiant l'élément"),
        ),
        migrations.AlterField(
            model_name='codeitem',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chemin ou URL vers une image générale du produit (optionnel)'),
        ),
        migrations.AlterField(
            model_name='codeitem',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.procedure', verbose_name='Lien vers la procédure associée, protection contre suppression'),
        ),
        migrations.AlterField(
            model_name='component',
            name='codeitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='tasks.codeitem', verbose_name='CodeItem associé'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/', verbose_name='Image du composant'),
        ),
        migrations.AlterField(
            model_name='component',
            name='item_id',
            field=models.CharField(max_length=50, verbose_name="Identifiant unique de l'élément"),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du composant'),
        ),
        migrations.AlterField(
            model_name='component',
            name='pos_x',
            field=models.PositiveIntegerField(default=0, help_text='px depuis le bord gauche', verbose_name='Position horizontale'),
        ),
        migrations.AlterField(
            model_name='component',
            name='pos_y',
            field=models.PositiveIntegerField(default=0, help_text='px depuis le bord supérieur', verbose_name='Position verticale'),
        ),
        migrations.AlterField(
            model_name='component',
            name='required_quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité requise du composant'),
        ),
        migrations.AlterField(
            model_name='component',
            name='z_index',
            field=models.PositiveIntegerField(default=1, help_text="Ordre d'empilement", verbose_name="Ordre d'affichage (z-index)"),
        ),
        migrations.AlterField(
            model_name='defect',
            name='authorized_by',
            field=models.CharField(max_length=100, verbose_name='Autorisé par'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_type',
            field=models.CharField(max_length=100, verbose_name='Type de défaut'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes supplémentaires'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='notify_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de notification'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.order', verbose_name='Commande liée'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='part_number',
            field=models.CharField(max_length=100, verbose_name='Numéro de pièce'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.workstep', verbose_name='Étape du processus'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de déclaration'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='unit_number',
            field=models.PositiveIntegerField(verbose_name='Numéro d’unité'),
        ),
        migrations.AlterField(
            model_name='order',
            name='codeitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.codeitem', verbose_name='Item codé'),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(verbose_name='Date limite de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lot_number',
            field=models.CharField(max_length=5, verbose_name='Numéro de lot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mo_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('shipped', 'Expédiée'), ('delivered', 'Livrée')], max_length=20, verbose_name='Statut de la commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='Date de la commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Identifiant de commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité commandée'),
        ),
        migrations.AlterField(
            model_name='ordercomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.component', verbose_name='Composant'),
        ),
        migrations.AlterField(
            model_name='ordercomponent',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Sélectionné'),
        ),
        migrations.AlterField(
            model_name='ordercomponent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='approved_by',
            field=models.CharField(max_length=200, verbose_name='Nom de la personne qui a approuvé la procédure'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='approved_date',
            field=models.DateField(verbose_name="Date d'approbation"),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='assembly_number',
            field=models.CharField(max_length=50, verbose_name="Numéro d'assemblage lié"),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=models.TextField(verbose_name='Description détaillée de la procédure'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la procédure'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='prepared_by',
            field=models.CharField(max_length=100, verbose_name='Nom de la personne qui a préparé la procédure'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='prepared_date',
            field=models.DateField(verbose_name='Date de préparation'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_number',
            field=models.CharField(max_length=50, verbose_name="Numéro d'identification de la procédure"),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='review_date',
            field=models.DateField(verbose_name='Date de révision'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='reviewed_by',
            field=models.CharField(max_length=200, verbose_name='Nom de la personne qui a révisé la procédure'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='revision_number',
            field=models.CharField(max_length=20, verbose_name='Numéro de révision de la procédure'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='stepprogress',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Étape complétée'),
        ),
        migrations.AlterField(
            model_name='stepprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de complétion'),
        ),
        migrations.AlterField(
            model_name='stepprogress',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.order', verbose_name='Commande concernée'),
        ),
        migrations.AlterField(
            model_name='stepprogress',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.workstep', verbose_name='Étape spécifique'),
        ),
        migrations.AlterField(
            model_name='stepprogress',
            name='unit_number',
            field=models.PositiveIntegerField(verbose_name='Numéro de l’unité de production'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tools/', verbose_name="Image de l'outil stockée dans le dossier 'tools/'"),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nom de l'outil"),
        ),
        migrations.AlterField(
            model_name='tool',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_items', to='tasks.procedure', verbose_name='Liaison vers la procédure, suppression en cascade'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité nécessaire (par défaut 1)'),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='description',
            field=models.TextField(verbose_name="Description de l'étape"),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='steps/', verbose_name="Image de l'étape"),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Miniature image'),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Titre de l'étape"),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='units_required',
            field=models.PositiveIntegerField(default=0, verbose_name='Unités nécessaires'),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL vidéo'),
        ),
        migrations.AlterField(
            model_name='workstepdefect',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes supplémentaires'),
        ),
        migrations.AlterField(
            model_name='workstepdefect',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.order', verbose_name='Commande concernée'),
        ),
        migrations.AlterField(
            model_name='workstepdefect',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité défectueuse'),
        ),
        migrations.AlterField(
            model_name='workstepdefect',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Signalé par'),
        ),
        migrations.AlterField(
            model_name='workstepdefect',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.workstep', verbose_name='Étape de travail'),
        ),
        migrations.AlterField(
            model_name='workstepdefect',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de signalement'),
        ),
        migrations.CreateModel(
            name='ComponentSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField(verbose_name='Unité de production')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Numéro de série')),
                ('component_name', models.CharField(max_length=100, verbose_name='Nom du composant (copié)')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.component', verbose_name='Composant lié')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.order', verbose_name='Commande')),
            ],
        ),
    ]
