# Generated by Django 5.2 on 2025-07-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_defect_options_alter_ordercomponent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentserial',
            name='gain',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentserial',
            name='volt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
    ]
