# Generated by Django 5.2 on 2025-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_componentserial_gain_componentserial_volt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentserial',
            name='gain',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
