# Generated by Django 5.2 on 2025-07-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_componentserial_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentserial',
            name='volt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
